on:
  push:
    branches:
      - master
      - 'gh-actions'
      - 'githubactions'
    paths-ignore:
      - 'python/**'

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    strategy:
      matrix:
        config:
          - r: '4.1.0'
            http-user-agent: 'github-actions'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.1.0-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.1.0-

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages("future.apply")
          install.packages(c("rms", "gbm", "caret", "e1071", "yardstick"))
          install.packages("pkgdown")
          remotes::install_github("ModelOriented/DrWhyTemplate")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = TRUE)'
