on:
  push:
    branches:
      - master
      - 'issue*'
      - 'gh-actions'
      - 'githubactions'
    paths:
      - '**.R'
      - '**.yaml'
      - '**.r'
      - '*DESCRIPTION'
      - '**.Rmd'
      - '**.rmd'
      - '**.rda'
      - '**.Rda'
      - '**.rds'
      - '**.Rds'
      - '!python/**'
  pull_request:
    branches:
      - master
    paths:
      - '**.R'
      - '**.r'
      - '*DESCRIPTION'
      - '**.Rmd'
      - '**.rmd'
      - '**.rda'
      - '**.Rda'
      - '**.rds'
      - '**.Rds'

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys:  macOS-r-4.0-1-

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "randomForest"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
